server:
  port: 7003

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/byebai95/config-repository.git
          username: byebai95
          password: 
          search-paths: config
          default-label: main
        bootstrap: true


