spring:
  application:
    name: server02
  cloud:
    config:
      uri: http://localhost:7003/
      profile: dev
      label: main

server:
  port: 6002

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false